const {test,expect}=require('@playwright/test');
function wav(){const n=8000*60,b=Buffer.alloc(44+n*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(8000,24);b.writeUInt32LE(16000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*2,40);return b;}
async function snap(page,info,name){await page.evaluate(async()=>{await Promise.all(document.getAnimations().filter(a=>a.effect.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{})));document.querySelectorAll('.toast').forEach(t=>t.remove());});await page.screenshot({path:info.outputPath(name)});}
async function seed(page,mobile){if(mobile)await page.setViewportSize({width:390,height:844});await page.addInitScript(()=>localStorage.setItem('playerium_auto_update_check','false'));await page.goto('/');await page.waitForFunction(()=>window.playerApp?.library.db);await page.locator('#hiddenAudioFilesPicker').setInputFiles(['First','Second','Third'].map(title=>({name:`Artist - ${title}.wav`,mimeType:'audio/wav',buffer:wav()})));await page.waitForFunction(()=>window.playerApp.library.getTracks().length===3);return page.evaluate(async()=>{const a=window.playerApp;for(const [i,t]of a.library.getTracks().entries()){t.album='Album';t.year=2024;t.pictureUrl='data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512"><rect width="512" height="512" fill="${['#9e3449','#395f87','#d39349'][i]}"/><circle cx="256" cy="256" r="160" fill="#ffffff20"/><circle cx="256" cy="256" r="65" fill="#121212"/></svg>`);}const p=await a.library.createPlaylist('Evening','Музыка для вечера');for(const t of a.library.getTracks())await a.library.addTrackToPlaylist(p.id,t.id);a.ui.refreshCurrentView();return p.id;});}
for(const mobile of [false,true]){
 test(`library search, grid, sorting, collection editing and focus (${mobile?'mobile':'desktop'})`,async({page},info)=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));const id=await seed(page,mobile);
  await snap(page,info,'home.png');
  await page.evaluate(()=>window.playerApp.ui.navigateTo({type:'library',title:'Моя медиатека'}));
  await page.getByRole('button',{name:'Поиск в медиатеке',exact:true}).click();await page.getByRole('searchbox',{name:'Найти в медиатеке'}).fill('Evening');await expect(page.locator('.mobile-lib-row')).toHaveCount(1);
  await page.getByRole('button',{name:'Показать сеткой',exact:true}).click();await expect(page.locator('.mobile-library-list')).toHaveClass(/library-grid/);await snap(page,info,'library-grid.png');
  await page.getByRole('button',{name:'Закрыть поиск',exact:true}).click();await page.locator('.library-sort').click();await page.locator('.surface-panel').getByText('По названию',{exact:true}).click();await expect(page.locator('.library-sort')).toContainText('По названию');const names=await page.locator('.mobile-lib-name').allTextContents();expect(names).toEqual([...names].sort((a,b)=>a.localeCompare(b,'ru')));
  await page.locator('.mobile-lib-row').filter({hasText:'Evening'}).click();await snap(page,info,'playlist.png');await page.locator('.collection-edit').click();
  await page.getByLabel('Название',{exact:true}).fill('Night');await page.getByLabel('Описание',{exact:true}).fill('Изменено');await page.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.locator('.view-title')).toHaveText('Night');expect(await page.evaluate(id=>window.playerApp.library.getPlaylistById(id).description,id)).toBe('Изменено');
  await page.locator('.collection-more').click();await page.keyboard.press('Escape');await expect(page.locator('.surface-panel')).toHaveCount(0);await expect(page.locator('.collection-more')).toBeFocused();
  await page.evaluate(()=>window.playerApp.ui.navigateTo({type:'artist',id:'Artist',title:'Artist'}));await expect(page.locator('.artist-discography .shelf-card')).toHaveCount(1);await snap(page,info,'artist.png');await page.locator('.artist-discography .shelf-card').click();await expect(page.locator('.view-title')).toHaveText('Album');await snap(page,info,'album.png');
  await page.evaluate(()=>window.playerApp.ui.navigateTo({type:'settings',title:'Настройки'}));await snap(page,info,'settings.png');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(mobile){expect(await page.locator('#app').evaluate(e=>e.getBoundingClientRect().top)).toBe(0);expect(await page.locator('#mobileNavBar').evaluate(e=>Math.round(e.getBoundingClientRect().bottom))).toBe(844);}expect(errors).toEqual([]);
 });
 test(`queue reorder and bulk removal keep current playback (${mobile?'mobile':'desktop'})`,async({page},info)=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));const id=await seed(page,mobile);await page.evaluate(id=>window.playerApp.ui.navigateTo({type:'playlist',id,title:'Evening'}),id);await page.locator('#btnHeroPlay').click();await page.waitForFunction(()=>window.playerApp.player.isPlaying);await page.evaluate(()=>{const p=window.playerApp.player;p.seekToTime(10);window.beforeQueue={id:p.currentTrack.id,src:p.audio.src,loads:0};p.audio.addEventListener('loadstart',()=>window.beforeQueue.loads++);window.originalOrder=p.queue.map(t=>t.title);});
  await page.evaluate(()=>window.playerApp.ui.openRightPanel('queue'));const upcoming=page.locator('.queue-item:not(.current)');await expect(upcoming).toHaveCount(2);await upcoming.first().locator('.queue-drag').focus();await page.keyboard.press('ArrowDown');
  const state=await page.evaluate(()=>{const p=window.playerApp.player;return {id:p.currentTrack.id,src:p.audio.src,loads:window.beforeQueue.loads,time:p.getCurrentTime(),order:p.queue.map(t=>t.title),old:window.originalOrder,playing:p.isPlaying,before:window.beforeQueue};});expect(state.id).toBe(state.before.id);expect(state.src).toBe(state.before.src);expect(state.loads).toBe(0);expect(state.time).toBeGreaterThanOrEqual(10);expect(state.playing).toBe(true);expect(state.order).toEqual([state.old[0],state.old[2],state.old[1]]);
  await snap(page,info,'queue.png');await upcoming.first().locator('input').check();await upcoming.last().locator('input').check();await page.getByRole('button',{name:'Удалить выбранные (2)',exact:true}).click();await expect(upcoming).toHaveCount(0);expect(await page.evaluate(()=>window.playerApp.player.currentTrack.id)).toBe(state.id);expect(await page.evaluate(()=>window.playerApp.player.isPlaying)).toBe(true);expect(errors).toEqual([]);
 });
}
test('mobile create, player context, share/menu, swipe close and narrow layout',async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));const id=await seed(page,true);await page.locator('#mobileNavCreate').click();await page.getByRole('button',{name:'Плейлист',exact:true}).click();await page.getByLabel('Название',{exact:true}).fill('Created');await page.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.locator('.view-title')).toHaveText('Created');await page.locator('.collection-more').click();expect(await page.evaluate(()=>window.playerApp.ui.handleBack())).toBe(true);await expect(page.locator('.surface-panel')).toHaveCount(0);await page.evaluate(()=>window.playerApp.ui.openRightPanel('queue'));expect(await page.evaluate(()=>window.playerApp.ui.handleBack())).toBe(true);await expect(page.locator('#rightPanel')).toHaveClass(/hidden/);
 await page.evaluate(()=>window.playerApp.ui.navigateTo({type:'album',id:'Album',extra:'Artist',title:'Album'}));await page.locator('#btnHeroPlay').click();await page.waitForFunction(()=>window.playerApp.player.isPlaying);await page.locator('#mobileMiniTitle').click();await expect(page.locator('.mobile-fs-context-subtitle')).toHaveText('Играет из альбома');await snap(page,info,'player.png');
 await page.locator('#btnMobileFsOptions').click();await page.keyboard.press('Escape');await expect(page.locator('.track-options-sheet')).toHaveCount(0);await expect(page.locator('#mobileFullscreenPlayer')).toHaveClass(/active/);
 const header=await page.locator('.mobile-fs-context').boundingBox();await page.mouse.move(header.x+header.width/2,header.y+header.height/2);await page.mouse.down();await page.mouse.move(header.x+header.width/2,header.y+header.height/2+120);await page.mouse.up();await expect(page.locator('#mobileFullscreenPlayer')).not.toHaveClass(/active/);
 await page.setViewportSize({width:320,height:640});await page.locator('#mobileNavLibrary').click();await snap(page,info,'narrow-library.png');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
});
